In [1]:
import numpy as np

In [3]:
minha_lista = [10,20,30]
minha_lista

[10, 20, 30]

In [5]:
np.array(minha_lista)

array([10, 20, 30])

In [7]:
minha_matriz = [(1,1,1),(2,2,2),(3,3,3),(4,4,4)]
np.array(minha_matriz)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [9]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [15]:
array = np.zeros((5,5,5))
array

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [33]:
a = np.random.randint(4,100,(5,7)) 
a

array([[97, 86, 90, 43, 17, 93, 46],
       [18, 23, 55, 14, 23, 32,  9],
       [ 6, 55, 81, 32, 91, 66, 36],
       [81, 32, 99, 16, 83, 62, 52],
       [32, 74, 14, 83, 50, 87,  7]])

In [37]:
b = np.random.rand(2,2) * 100
b

array([[81.61882037, 44.09463841],
       [27.03018185,  0.5614974 ]])

In [65]:
a[0:2]

array([[17, 60],
       [78, 78]])

In [67]:
import pandas as pd

In [80]:
labels = ['a','b','c','d','e','f','g']
lista = [10,20,30,40,50,60,70]

In [82]:
pd.Series(data=lista,index=labels)

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

In [99]:
np.random.seed(10) 

df = pd.DataFrame(np.random.randn(5,4),index='a b c d e'

In [102]:
df = pd.DataFrame(np.random.randn(5,4),index='a b c d e'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
a  1.331587  0.715279 -1.545400 -0.008384
b  0.621336 -0.720086  0.265512  0.108549
c  0.004291 -0.174600  0.433026  1.203037
d -0.965066  1.028274  0.228630  0.445138
e -1.136602  0.135137  1.484537 -1.079805

In [108]:
df.loc['c','Y']

0.433026189953598

In [113]:
#probalidade